version: '2'
services:
  driver:
    network_mode: host
    image: jeguzzi/drone_arena:bebop
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./logs:/root/.ros/log:rw
    command: roslaunch bebop_driver bebop_node.launch
    env_file:
      - ./ros.env
  teleop:
    privileged: true
    network_mode: host
    image: jeguzzi/drone_arena:bebop
    volumes:
      - ./logs:/root/.ros/log:rw
    command: roslaunch bebop_tools joy_teleop.launch
    env_file:
      - ./ros.env
